### ISSUE TITLE
Working (non-fucked up) profiles

### ISSUE THREAD

**Issue by jko64** [jko64/bytehax#3]

**Comment by whatsinthedev** [comment]
Profiles look _lovely_:
![image](https://user-images.githubusercontent.com/96445516/153674456-6f30b137-80f0-4d1f-a1b2-ea2b7678721f.png)

**Comment by TheTown777** [comment]
> Profiles look _lovely_:
> ![image](https://user-images.githubusercontent.com/96445516/153674456-6f30b137-80f0-4d1f-a1b2-ea2b7678721f.png)
what web browser and os is that?

**Comment by jko64** [comment]
> Profiles look _lovely_:
> ![image](https://user-images.githubusercontent.com/96445516/153674456-6f30b137-80f0-4d1f-a1b2-ea2b7678721f.png)
> what web browser and os is that?

Chrome Stable 94 on Chrome OS

**Comment by jko64** [comment]
It’s not the browser because that’s how it looks everywhere

**Comment by jko64** [comment]
too late bootstrap will go bye-bye
